# Generated by Django 2.2.5 on 2019-11-26 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'palabra clave',
                'verbose_name_plural': 'palabras claves',
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('always', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'fuente',
                'verbose_name_plural': 'fuentes',
                'db_table': 'news_sources',
            },
        ),
        migrations.CreateModel(
            name='SourceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='noticrawler.Source')),
            ],
            options={
                'verbose_name': 'enlace a fuente',
                'verbose_name_plural': 'enlaces a fuentes',
                'db_table': 'source_links',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('image', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('is_sent', models.BooleanField(default=False)),
                ('source_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='noticrawler.SourceLink')),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
                'db_table': 'news_posts',
            },
        ),
    ]
