# Generated by Django 2.2.5 on 2019-10-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_registration', '0006_auto_20191010_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='_type',
            field=models.CharField(choices=[('MUST', 'Debe'), ('MUST_NOT', 'No debe')], db_column='m_type', default='MUST', max_length=10, verbose_name='Tipo'),
        ),
    ]
