# Generated by Django 2.2.5 on 2019-10-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_registration', '0004_auto_20191003_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdetails',
            name='document_date',
            field=models.DateTimeField(null=True),
        ),
    ]
