# Generated by Django 2.2.5 on 2019-10-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_registration', '0005_documentdetails_document_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdetails',
            name='document_date',
            field=models.DateField(null=True, verbose_name='Fecha Documento'),
        ),
    ]
