# Generated by Django 2.2.5 on 2019-11-26 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_registration', '0007_mandate__type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='document_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='doc_registration.DocumentDetails', verbose_name='Documento'),
            preserve_default=False,
        ),
    ]
