# Generated by Django 2.2.5 on 2019-11-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_registration', '0008_mandate_document_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandate',
            name='document',
        ),
    ]
