# Generated by Django 2.2.5 on 2019-11-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_registration', '0009_remove_mandate_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(max_length=300, null=True, verbose_name='Descripción'),
        ),
    ]
