# Generated by Django 2.2.5 on 2019-11-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_registration', '0010_auto_20191126_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción'),
        ),
    ]
