# Generated by Django 2.2.5 on 2019-11-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_registration', '0011_auto_20191126_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandateTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doc_registration.Mandate')),
            ],
        ),
    ]
